#!/usr/bin/env python3
"""Push cloud-burst INPUT artifacts to R2 so pods can pull them.

  --backbones     mirror the local-only pretrained baseline backbones (crosshar, limubert)
                  -> halo/ckpt/baselines/<name>/... (tiny, ~260KB each)
  --requirements  freeze the current venv's core deps -> cloud/requirements-core.txt and upload
                  -> halo/meta/requirements-core.txt  (torch/vision/audio/clip are EXCLUDED here;
                  bootstrap.sh installs the torch stack from the cu128 index and CLIP from git)
  --sessions      (DEFERRED) build+upload the 41GB HALO raw session store as a zstd bundle
                  -> halo/data/sessions-<hash>.tar.zst  (only needed to burst HALO training)

Default (no flags): --backbones + --requirements (the baseline-pod inputs).
Source cloud/.env first:  set -a; . cloud/.env; set +a
"""

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import r2_util as R2  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# local-only pretrained backbones -> R2 key under ckpt/baselines/<name>/
BACKBONES = {
    "crosshar": PROJECT_ROOT / "auxiliary_repos/CrossHAR/saved/pretrain_base_combined_train_20_120/model_masked_6_1.pt",
    "limubert": PROJECT_ROOT / "auxiliary_repos/LIMU-BERT-Public/saved/pretrain_base_combined_train_20_120/pretrained_combined.pt",
}

# torch stack + git-installed packages are handled specially in bootstrap.sh, not the lock file.
REQ_EXCLUDE_PREFIXES = ("torch", "torchvision", "torchaudio", "clip", "nvidia-", "triton")


def push_backbones(s3):
    print("Mirroring baseline backbones -> R2:")
    for name, path in BACKBONES.items():
        if not path.exists():
            print(f"  [skip] {name}: {path} absent"); continue
        R2.upload(s3, path, R2.key("ckpt", "baselines", name, path.name))


def push_requirements(s3):
    print("Freezing core requirements:")
    freeze = subprocess.check_output([sys.executable, "-m", "pip", "freeze"], text=True).splitlines()
    core = []
    for line in freeze:
        name = line.split("==")[0].split(" @ ")[0].strip().lower()
        if not line or line.startswith("-e ") or "@ file://" in line:
            continue
        if any(name.startswith(p) for p in REQ_EXCLUDE_PREFIXES):
            continue
        core.append(line)
    out = PROJECT_ROOT / "cloud" / "requirements-core.txt"
    header = ("# Auto-generated by cloud/push_artifacts.py --requirements.\n"
              "# torch/torchvision/torchaudio (cu128 index) + CLIP (git) are installed separately\n"
              "# by bootstrap.sh, NOT from this file.\n")
    out.write_text(header + "\n".join(sorted(core)) + "\n")
    print(f"  wrote {out} ({len(core)} pkgs)")
    R2.upload(s3, out, R2.key("meta", "requirements-core.txt"))


def push_sessions(s3):
    print("--sessions is DEFERRED (41GB HALO session store). Decide HALO-on-pods first; then this\n"
          "will zstd `data/` and upload halo/data/sessions-<hash>.tar.zst. Not implemented yet.")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--backbones", action="store_true")
    ap.add_argument("--requirements", action="store_true")
    ap.add_argument("--sessions", action="store_true")
    args = ap.parse_args()
    if not (args.backbones or args.requirements or args.sessions):
        args.backbones = args.requirements = True  # default

    s3 = R2.client()
    if args.backbones:
        push_backbones(s3)
    if args.requirements:
        push_requirements(s3)
    if args.sessions:
        push_sessions(s3)
    print("done.")


if __name__ == "__main__":
    main()
